// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace cadastro_pacientes.Migrations
{
    [DbContext(typeof(ClinicaContext))]
    [Migration("20230109190603_role")]
    partial class role
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cadastro_pacientes.Models.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext")
                        .HasColumnName("CPF");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext")
                        .HasColumnName("ENDERECO");

                    b.Property<long>("Ficha")
                        .HasColumnType("bigint")
                        .HasColumnName("FICHA");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NASCIMENTO");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("longtext")
                        .HasColumnName("NATURALIDADE");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("Profissao")
                        .HasColumnType("longtext")
                        .HasColumnName("PROFISSAO");

                    b.Property<string>("Rg")
                        .HasColumnType("longtext")
                        .HasColumnName("RG");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext")
                        .HasColumnName("SEXO");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("TELEFONE");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext")
                        .HasColumnName("UF");

                    b.HasKey("Id");

                    b.ToTable("paciente");
                });

            modelBuilder.Entity("cadastro_pacientes.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CODIGO");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("Role")
                        .HasColumnType("longtext")
                        .HasColumnName("ROLE");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext")
                        .HasColumnName("USUARIO");

                    b.HasKey("Id");

                    b.ToTable("funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
